name: Scan Code for Secrets
'on':
  push:
    branches:
      - '**'
    tags:
      - '!**'
jobs:
  detect-secrets:
    name: check-for-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: detect-secrets
      - name: Run Yelp's detect-secrets (scan)
        run: >-
          detect-secrets scan --exclude-lines "secretName:" --exclude-secrets
          "abc123xyz456" --exclude-secrets "eks-codecademy-com-prod-api-tls" >
          ./.secrets.baseline
      - name: Run Yelp's detect-secrets (audit)
        run: detect-secrets audit ./.secrets.baseline
